### PR TITLE
Booking page aljayz

### PR DESCRIPTION
**Pull request by Aljayz**
Made a booking page from team Eureka

### CODE REVIEW

**Review by lavahotsnacks — COMMENTED** [review]
basically just a color grey background was added to the booking page. maybe remove the "Hellow" filler text to keep it professional.

**Comment by Aljayz** [comment]
Okay, I forgot to remove. I'm just testing the container

**Comment by a1-hanif** [comment]
Good day, please do check your authentication with your QA

**Review by Aljayz — COMMENTED** [review]
I created a responsive **Booking Page UI**, Also, I disabled the **SearchbarComponent** when in the booking page.

**Comment by Reyn4ldo** [comment]
try again

**Review by Aljayz — COMMENTED** [review]
I created Booking Page UI from team Eureka

**Pull request closed without merging**
